security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
 
    providers:
        in_database: #nom du provider
            entity:
                class: App\Entity\User
                property: email
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ #en mode développement on a accès au profiler par le chemmin /_profiler
            security: false
        main:
            lazy: true # le site (en dehors des parties réservées est accessible en anonyme)
            provider: in_database # defini dans providers

            form_login:
                login_path: connexion
                check_path: connexion
                enable_csrf: true
                default_target_path: roles

            logout:
                path: deconnexion
                target: accueil
            custom_authenticator: App\Security\SecurityAuthenticator

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/profil, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/deconnexion, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/inscription, roles: IS_ANONYMOUS }
         - { path: ^/connexion, roles: IS_ANONYMOUS }
         
    role_hierarchy:
         ROLE_ADMIN: [ROLE_REV, ROLE_USER ]
         ROLE_REV: [ROLE_USER]
         ROLE_TOUT: [ROLE_ADMIN, ROLE_REV, ROLE_USER]